version = 1
SPDX-PackageName = "sap-community-abap-developer-challeng"
SPDX-PackageSupplier = "shilpa.shankar@sap.com"  
SPDX-PackageDownloadLocation = "https://github.com/sap-samples/sap-community-abap-developer-challenge"  
SPDX-PackageComment = "This project is part of the SAP ABAP Escape House May 2025 Challenge. It may contain calls to SAP APIs and is based on the original challenge repository from SAP: https://github.com/sap-samples/sap-community-abap-developer-challenge."

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP SE or an SAP affiliate company and sap-community-abap-developer-challenge contributors"
SPDX-License-Identifier = "Apache-2.0"
